language: generic

services:
  - docker

deploy:
  - provider: elasticbeanstalk
    region: us-east-1
    app: "mmy-first-app"
    env: "Mmyfirstapp-env"

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket_name: "my-first-app-bucket-1"

    bucket_path: "docker"

    on:
      branch: main

  - provider: elasticbeanstalk
    region: ap-south-1
    app: "test-app"
    env: "Testapp-env"

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket_name: "my-first-app-bucket-1"
  
    bucket_path: "docker"

    on:
      branch: testing
